# Site settings
title: Static Chuck! A test.
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
baseurl: ""
url: "http://www.chuckmasterson.com/staticchuck-test/"
locale: en
github_username: chuckmasterson

# Build settings
markdown: kramdown

staticman:
  api: "https://hkstaticchuck.herokuapp.com/v3/entry/github/chuckmasterson/staticchuck-test/master/comments"
  path: "_data/comments/test-slug"
